name: SwapPlugin
version: ${project.version}
main: net.kunmc.lab.swapplugin.SwapPlugin
api-version: 1.15
authors: [ YukiAt ]

commands:
  swap:
    permission: swapplugin.swap

permissions:
  swapplugin.swap:
    default: op
